name: Python CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install npm
        run: npm install
      - name: Install 
        run: make setup
      - name: build
        run: make build
      - name: Start
        run: make start
      - name: Run test
        run: make test
      - name: Run linter
        run: make lint